/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import bancoDAO.BancoDAO;
import classes.*;
import static java.lang.System.exit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    BancoDAO bancodao; 
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jtbP_vendas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_nomeDR = new javax.swing.JTextField();
        jtf_sobrenomeDR = new javax.swing.JTextField();
        jtf_cpfDR = new javax.swing.JFormattedTextField();
        jtf_telefoneDR = new javax.swing.JFormattedTextField();
        jbt_inserirDR = new javax.swing.JButton();
        jbbt_removerDR = new javax.swing.JButton();
        jbt_atualizarDR = new javax.swing.JButton();
        jbt_mostrarDR = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtf_cpfB_DR = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jbt_buscarDR = new javax.swing.JButton();
        jbt_limpaTelaDR = new javax.swing.JButton();
        jtf_rendamensalDR = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_codR = new javax.swing.JFormattedTextField();
        jtf_areaR = new javax.swing.JFormattedTextField();
        jtf_ruaR = new javax.swing.JFormattedTextField();
        jtf_numR = new javax.swing.JFormattedTextField();
        jtf_bairroR = new javax.swing.JFormattedTextField();
        jbt_inserirR = new javax.swing.JButton();
        jbt_removerR = new javax.swing.JButton();
        jbt_atualizarR = new javax.swing.JButton();
        jbt_mostrarR = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtf_bairro_BR = new javax.swing.JTextField();
        jbt_buscarR = new javax.swing.JButton();
        jbt_limparTelaR = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtf_cpfV = new javax.swing.JFormattedTextField();
        jtf_codrV = new javax.swing.JFormattedTextField();
        jtf_dtV = new javax.swing.JFormattedTextField();
        jtf_valorV = new javax.swing.JFormattedTextField();
        jbt_limparTelaV = new javax.swing.JButton();
        jbt_inserirV = new javax.swing.JButton();
        jbt_removerV = new javax.swing.JButton();
        jbt_atualizarV = new javax.swing.JButton();
        jbt_mostrarV = new javax.swing.JButton();
        jbt_vendas6M = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jtf_codVrem = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtf_codV = new javax.swing.JFormattedTextField();
        jbt_sair = new javax.swing.JButton();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbP_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbP_vendasMouseClicked(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Sobrenome");

        jLabel3.setText("CPF:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Renda Mensal");

        try {
            jtf_cpfDR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtf_cpfDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cpfDRActionPerformed(evt);
            }
        });

        try {
            jtf_telefoneDR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jbt_inserirDR.setText("INSERIR");
        jbt_inserirDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirDRActionPerformed(evt);
            }
        });

        jbbt_removerDR.setText("REMOVER");
        jbbt_removerDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbt_removerDRActionPerformed(evt);
            }
        });

        jbt_atualizarDR.setText("ATUALIZAR");
        jbt_atualizarDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarDRActionPerformed(evt);
            }
        });

        jbt_mostrarDR.setText("MOSTRAR");
        jbt_mostrarDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_mostrarDRActionPerformed(evt);
            }
        });

        jLabel6.setText("BUSCA POR CPF");

        try {
            jtf_cpfB_DR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtf_cpfB_DR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cpfB_DRActionPerformed(evt);
            }
        });

        jLabel7.setText("Informe o CPF");

        jbt_buscarDR.setText("BUSCAR");
        jbt_buscarDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscarDRActionPerformed(evt);
            }
        });

        jbt_limpaTelaDR.setText("LIMPAR TELA");
        jbt_limpaTelaDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_limpaTelaDRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_cpfB_DR, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt_buscarDR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbt_inserirDR, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbbt_removerDR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_atualizarDR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_mostrarDR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_nomeDR)
                            .addComponent(jtf_sobrenomeDR)
                            .addComponent(jtf_cpfDR)
                            .addComponent(jtf_telefoneDR, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jtf_rendamensalDR)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jbt_limpaTelaDR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_nomeDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_sobrenomeDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_cpfDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_telefoneDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_rendamensalDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_inserirDR)
                    .addComponent(jbbt_removerDR)
                    .addComponent(jbt_atualizarDR)
                    .addComponent(jbt_mostrarDR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_cpfB_DR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_buscarDR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_limpaTelaDR)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jtbP_vendas.addTab("Dono da Residência", jPanel1);

        jLabel8.setText("Código da Residência:");

        jLabel9.setText("Área:");

        jLabel10.setText("Endereço");

        jLabel11.setText("Rua:");

        jLabel12.setText("Número:");

        jLabel13.setText("Bairro:");

        try {
            jtf_codR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtf_areaR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jbt_inserirR.setText("INSERIR");
        jbt_inserirR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirRActionPerformed(evt);
            }
        });

        jbt_removerR.setText("REMOVER");

        jbt_atualizarR.setText("ATUALIZAR");

        jbt_mostrarR.setText("MOSTRAR");

        jLabel15.setText("BUSCA POR BAIRRO");

        jLabel16.setText("Informe o Bairro:");

        jbt_buscarR.setText("BUSCAR");

        jbt_limparTelaR.setText("LIMPAR TELA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_codR)
                            .addComponent(jtf_areaR)
                            .addComponent(jtf_ruaR)
                            .addComponent(jtf_numR)
                            .addComponent(jtf_bairroR, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_bairro_BR))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbt_inserirR, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_removerR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_atualizarR, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbt_mostrarR, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jbt_buscarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jbt_limparTelaR)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_codR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtf_areaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_ruaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtf_numR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtf_bairroR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_inserirR)
                    .addComponent(jbt_removerR)
                    .addComponent(jbt_atualizarR)
                    .addComponent(jbt_mostrarR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtf_bairro_BR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_buscarR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_limparTelaR)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jtbP_vendas.addTab("Residência", jPanel2);

        jLabel17.setText("Código da Venda:");

        jLabel18.setText("CPF do Dono:");

        jLabel19.setText("Código da Residência: ");

        jLabel20.setText("Data da Venda:");

        jLabel21.setText("Valor de Venda:");

        try {
            jtf_cpfV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtf_codrV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtf_dtV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jtf_valorV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        jbt_limparTelaV.setText("LIMPAR TELA");

        jbt_inserirV.setText("INSERIR");

        jbt_removerV.setText("REMOVER");

        jbt_atualizarV.setText("ATUALIZAR");

        jbt_mostrarV.setText("MOSTRAR");

        jbt_vendas6M.setText("VENDAS NOS ULTIMOS SEIS MESES");

        jLabel22.setText("Código da Venda");

        jLabel23.setText("ATENÇÃO: Se você não lembra o código de venda, clique em mostrar");

        try {
            jtf_codV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#U#L#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_cpfV)
                    .addComponent(jtf_codrV, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jtf_dtV)
                    .addComponent(jtf_valorV)
                    .addComponent(jtf_codV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jbt_inserirV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jbt_atualizarV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbt_mostrarV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jbt_limparTelaV)
                                    .addGap(203, 203, 203))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbt_vendas6M, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtf_codVrem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbt_removerV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(66, 66, 66)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtf_codV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jtf_cpfV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtf_codrV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtf_dtV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jtf_valorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_inserirV)
                    .addComponent(jbt_atualizarV)
                    .addComponent(jbt_mostrarV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_vendas6M)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_removerV)
                    .addComponent(jLabel22)
                    .addComponent(jtf_codVrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbt_limparTelaV)
                .addContainerGap())
        );

        jtbP_vendas.addTab("Vendas", jPanel3);

        jbt_sair.setText("SAIR");
        jbt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbP_vendas)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jbt_sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbP_vendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_sair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_cpfB_DRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cpfB_DRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cpfB_DRActionPerformed

    private void jbt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_sairActionPerformed
        exit(0);
    }//GEN-LAST:event_jbt_sairActionPerformed

    private void jtbP_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbP_vendasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbP_vendasMouseClicked

    private void jbt_inserirDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirDRActionPerformed
        if(jtf_cpfDR.getText().equals("           ")){
            JOptionPane.showMessageDialog(null, "PARA INSERIR COMPLETE TODOS OS CAMPOS");
        }else{
                       
            try {
                bancodao = new BancoDAO();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Dono dono = new Dono();
            
            dono.setCpf(jtf_cpfDR.getText());
            dono.setNome(jtf_nomeDR.getText()+" "+jtf_sobrenomeDR.getText());
            dono.setTelefone(jtf_telefoneDR.getText());
            dono.setRendaMensal(Float.parseFloat(jtf_rendamensalDR.getText()));
                    
            bancodao.insertDono(dono);
            limpartelaDono();
            
        }
    }//GEN-LAST:event_jbt_inserirDRActionPerformed

    private void jtf_cpfDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cpfDRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cpfDRActionPerformed

    private void jbt_limpaTelaDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_limpaTelaDRActionPerformed
        limpartelaDono();
    }//GEN-LAST:event_jbt_limpaTelaDRActionPerformed

    private void jbbt_removerDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbt_removerDRActionPerformed
        if(jtf_cpfDR.getText().equals("           ")){
            JOptionPane.showMessageDialog(null, "INFORME O CPF NO CAMPO ACIMA PARA REMOVER");
        }else{
                        
            try {
                bancodao = new BancoDAO();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           bancodao.excluirDono(jtf_cpfDR.getText());
           limpartelaDono();
            
        }
                
    }//GEN-LAST:event_jbbt_removerDRActionPerformed

    private void jbt_atualizarDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarDRActionPerformed
        if(jtf_cpfDR.getText().equals("           ")){
            JOptionPane.showMessageDialog(null, "PARA ATUALIZAR COMPLETE TODOS OS CAMPOS");
        }else{
                       
            try {
                bancodao = new BancoDAO();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Dono dono = new Dono();
            
            dono.setCpf(jtf_cpfDR.getText());
            dono.setNome(jtf_nomeDR.getText()+" "+jtf_sobrenomeDR.getText());
            dono.setTelefone(jtf_telefoneDR.getText());
            dono.setRendaMensal(Float.parseFloat(jtf_rendamensalDR.getText()));
                    
            bancodao.updateDono(dono);
            limpartelaDono();
            
        }   
    }//GEN-LAST:event_jbt_atualizarDRActionPerformed

    private void jbt_mostrarDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_mostrarDRActionPerformed
        TelaDonos tela2 =  new TelaDonos();
        tela2.setVisible(true);
    }//GEN-LAST:event_jbt_mostrarDRActionPerformed

    private void jbt_buscarDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscarDRActionPerformed
        if(jtf_cpfB_DR.getText().equals("           ")){
            JOptionPane.showMessageDialog(null, "INFORME O CPF NO CAMPO AO LADO PARA RBUSCAR");
        }else{
                        
            try {
                bancodao = new BancoDAO();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           ArrayList <Dono> listadonos = bancodao.mostraDono(0, jtf_cpfB_DR.getText());
        
           for(Dono dono : listadonos){

                jtf_cpfDR.setText(dono.getCpf());
                String a[] = dono.getNome().split(" ", 2);
                jtf_nomeDR.setText(a[0]);
                jtf_sobrenomeDR.setText(a[1]);
                jtf_telefoneDR.setText(dono.getTelefone());
                jtf_rendamensalDR.setText(Float.toString(dono.getRendaMensal()));
                jtf_cpfB_DR.setText("");

           }            
        }
           
    }//GEN-LAST:event_jbt_buscarDRActionPerformed

    private void jbt_inserirRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirRActionPerformed
        if(jtf_codR.getText().equals("               ")){
            JOptionPane.showMessageDialog(null, "PARA INSERIR COMPLETE TODOS OS CAMPOS");
        }else{
                       
            try {
                bancodao = new BancoDAO();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Dono dono = new Dono();
            
            dono.setCpf(jtf_cpfDR.getText());
            dono.setNome(jtf_nomeDR.getText()+" "+jtf_sobrenomeDR.getText());
            dono.setTelefone(jtf_telefoneDR.getText());
            dono.setRendaMensal(Float.parseFloat(jtf_rendamensalDR.getText()));
                    
            bancodao.insertDono(dono);
            limpartelaDono();
            
        }
    }//GEN-LAST:event_jbt_inserirRActionPerformed

    private void limpartelaDono(){
        
            jtf_cpfDR.setText("");
            jtf_nomeDR.setText("");
            jtf_sobrenomeDR.setText("");
            jtf_telefoneDR.setText("");
            jtf_rendamensalDR.setText("");
            jtf_cpfB_DR.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbbt_removerDR;
    private javax.swing.JButton jbt_atualizarDR;
    private javax.swing.JButton jbt_atualizarR;
    private javax.swing.JButton jbt_atualizarV;
    private javax.swing.JButton jbt_buscarDR;
    private javax.swing.JButton jbt_buscarR;
    private javax.swing.JButton jbt_inserirDR;
    private javax.swing.JButton jbt_inserirR;
    private javax.swing.JButton jbt_inserirV;
    private javax.swing.JButton jbt_limpaTelaDR;
    private javax.swing.JButton jbt_limparTelaR;
    private javax.swing.JButton jbt_limparTelaV;
    private javax.swing.JButton jbt_mostrarDR;
    private javax.swing.JButton jbt_mostrarR;
    private javax.swing.JButton jbt_mostrarV;
    private javax.swing.JButton jbt_removerR;
    private javax.swing.JButton jbt_removerV;
    private javax.swing.JButton jbt_sair;
    private javax.swing.JButton jbt_vendas6M;
    private javax.swing.JTabbedPane jtbP_vendas;
    private javax.swing.JFormattedTextField jtf_areaR;
    private javax.swing.JFormattedTextField jtf_bairroR;
    private javax.swing.JTextField jtf_bairro_BR;
    private javax.swing.JFormattedTextField jtf_codR;
    private javax.swing.JFormattedTextField jtf_codV;
    private javax.swing.JTextField jtf_codVrem;
    private javax.swing.JFormattedTextField jtf_codrV;
    private javax.swing.JFormattedTextField jtf_cpfB_DR;
    private javax.swing.JFormattedTextField jtf_cpfDR;
    private javax.swing.JFormattedTextField jtf_cpfV;
    private javax.swing.JFormattedTextField jtf_dtV;
    private javax.swing.JTextField jtf_nomeDR;
    private javax.swing.JFormattedTextField jtf_numR;
    private javax.swing.JTextField jtf_rendamensalDR;
    private javax.swing.JFormattedTextField jtf_ruaR;
    private javax.swing.JTextField jtf_sobrenomeDR;
    private javax.swing.JFormattedTextField jtf_telefoneDR;
    private javax.swing.JFormattedTextField jtf_valorV;
    // End of variables declaration//GEN-END:variables
}
